config/routes.rb
Rails.application.routes.draw do
  resources :things, only: [:new, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/health.rb
module Health
  def self.healthy?
    @services.all?(&:healthy?)
  end

  def self.services
    @services ||= []
  end

  Service = Struct.new(:name, :health_check) do
    def healthy?
      health_check.call
    end
  end
end

app/models/testing.rb
# class Testing < ActiveRecord::Base
# end

app/models/thing.rb
class Thing
  attr_reader :id, :name

  def initialize(id: nil, name: "")
    @id = id || SecureRandom.uuid
    @name = name
  end

  def as_json
    {
      'id' => id,
      'name' => name,
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/health_controller.rb
class HealthController < ApplicationController
  def show
    respond_to do |format|
      format.html do
        @health = Health
      end
      format.json do
        status = Health.healthy? ? 200 : 503
        render json: HealthJson.new(Health), status: status
      end
    end
  end
end

app/controllers/testings_controller.rb
class TestingsController < ApplicationController
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.new(id: params[:id])
  end

  # PUT /things
  # PUT /things.json
  def update
    @thing = Thing.new(id: params[:id], name: params[:name])
    PublishThingJob.perform_later(@thing.as_json)
    redirect_to edit_thing_path(id: @thing.id)
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    # FIXME: tombstone
    render text: '¯\_(ツ)_/¯', status: 500
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/testings_helper.rb
module TestingsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/health/show.html.erb
<h1>Health</h1>
<dl>
  <% @health.services.each do |service| %>
  <dt><%= service.name %></dt>
  <dd><%= service.healthy? %></dd>
  <% end %>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/things/_form.html.erb
<%= form_tag(thing_path(id: thing.id), method: :put) do |f| %>
  <div class="field">
    <%= label_tag :name %>
    <%= text_field_tag :name, thing.name %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'New', new_thing_path %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form', thing: @thing %>